//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPaymentsLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportToDBF
    {
        public int Id { get; set; }
        public int KB_A { get; set; }
        public string KK_A { get; set; }
        public int KB_B { get; set; }
        public string KK_B { get; set; }
        public bool DK { get; set; }
        public int SUMMA { get; set; }
        public string VID { get; set; }
        public string NDOC { get; set; }
        public int I_VA { get; set; }
        public System.DateTime DA { get; set; }
        public Nullable<System.DateTime> DA_DOC { get; set; }
        public string NK_A { get; set; }
        public string NK_B { get; set; }
        public string NAZN { get; set; }
        public string KOD_A { get; set; }
        public string KOD_B { get; set; }
        public string CPU { get; set; }
        public bool Confirmed { get; set; }
        public string FileName { get; set; }
    }
}
