//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPaymentsLoader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Payments_OBEntities : DbContext
    {
        public Payments_OBEntities()
            : base("name=Payments_OBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExportToDBF> ExportToDBF { get; set; }
        public virtual DbSet<RawXlsData> RawXlsData { get; set; }
        public virtual DbSet<vw_paymentsAccountTemplates> vw_paymentsAccountTemplates { get; set; }
    
        public virtual int up_upload_to_dbf(Nullable<int> account_id)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_upload_to_dbf", account_idParameter);
        }
    }
}
