//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPaymentsLoader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Payments_OBEntities : DbContext
    {
        public Payments_OBEntities()
            : base("name=Payments_OBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RawXlsData> RawXlsData { get; set; }
        public virtual DbSet<vw_paymentsAccountTemplates> vw_paymentsAccountTemplates { get; set; }
        public virtual DbSet<ExportToDBF> ExportToDBF { get; set; }
    
        public virtual int up_upload_to_dbf(Nullable<int> account_id)
        {
            var account_idParameter = account_id.HasValue ?
                new ObjectParameter("account_id", account_id) :
                new ObjectParameter("account_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_upload_to_dbf", account_idParameter);
        }
    
        public virtual int up_create_payments(Nullable<int> template_id)
        {
            var template_idParameter = template_id.HasValue ?
                new ObjectParameter("template_id", template_id) :
                new ObjectParameter("template_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_create_payments", template_idParameter);
        }
    
        public virtual int up_export_data_set_confirmed(string file_name)
        {
            var file_nameParameter = file_name != null ?
                new ObjectParameter("file_name", file_name) :
                new ObjectParameter("file_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_export_data_set_confirmed", file_nameParameter);
        }
    
        public virtual int up_export_data_update(string value)
        {
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_export_data_update", valueParameter);
        }
    
        public virtual int up_merge_template(Nullable<int> template_id, string cODE, Nullable<int> mFO, string account, string narrative, string templateName, string accountName)
        {
            var template_idParameter = template_id.HasValue ?
                new ObjectParameter("template_id", template_id) :
                new ObjectParameter("template_id", typeof(int));
    
            var cODEParameter = cODE != null ?
                new ObjectParameter("CODE", cODE) :
                new ObjectParameter("CODE", typeof(string));
    
            var mFOParameter = mFO.HasValue ?
                new ObjectParameter("MFO", mFO) :
                new ObjectParameter("MFO", typeof(int));
    
            var accountParameter = account != null ?
                new ObjectParameter("Account", account) :
                new ObjectParameter("Account", typeof(string));
    
            var narrativeParameter = narrative != null ?
                new ObjectParameter("Narrative", narrative) :
                new ObjectParameter("Narrative", typeof(string));
    
            var templateNameParameter = templateName != null ?
                new ObjectParameter("TemplateName", templateName) :
                new ObjectParameter("TemplateName", typeof(string));
    
            var accountNameParameter = accountName != null ?
                new ObjectParameter("AccountName", accountName) :
                new ObjectParameter("AccountName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_merge_template", template_idParameter, cODEParameter, mFOParameter, accountParameter, narrativeParameter, templateNameParameter, accountNameParameter);
        }
    }
}
