//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPaymentsLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawXlsData
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string row_1 { get; set; }
        public string row_2 { get; set; }
        public string row_3 { get; set; }
        public string row_4 { get; set; }
        public string row_5 { get; set; }
        public string row_6 { get; set; }
        public string row_7 { get; set; }
        public string row_8 { get; set; }
        public string row_9 { get; set; }
        public string row_10 { get; set; }
        public string row_11 { get; set; }
        public string row_12 { get; set; }
        public string row_13 { get; set; }
        public bool Confirmed { get; set; }
        public System.DateTime FileDate { get; set; }
    }
}
